import React from 'react';
import { useCurrentFrame, useVideoConfig, interpolate } from 'remotion';
import { fadeOut, sp, blurFade } from '../../common/utils';
import { SceneCanvas, PastelBackground, SAFE_H } from '../../common/components';
import { FONT_HEAD, FONT_MONO } from '../../common/fonts';

// ─────────────────────────────────────────────────────────────────────────────
//  Slide 4 — Verification & Ownership (Rule #2)
//
//  "If You Can't Explain It, Don't Commit It."
//  Visual: Code block with "REVIEWED" approval stamp overlay
//  3 bullet points
// ─────────────────────────────────────────────────────────────────────────────

const ORANGE = '#FF6B2B';
const BLACK  = '#0A0A0A';
const GREEN  = '#10B981';

const BULLETS = [
  { bold: 'Treat AI code', rest: ' as an untrusted PR from a junior developer.' },
  { bold: 'Line-by-line review', rest: ' is mandatory before merging any AI snippet.' },
  { bold: 'Code ownership:', rest: ' you take full responsibility for every bug the prompt generates.' },
];

const CODE_LINES = [
  { num: '1',  text: 'async function processPayment(order) {', color: '#F2ECE4' },
  { num: '2',  text: '  // generated by AI — needs review', color: '#FF9060' },
  { num: '3',  text: '  const charge = await stripe.charge({', color: '#F2ECE4' },
  { num: '4',  text: '    amount: order.total,', color: 'rgba(242,236,228,0.65)' },
  { num: '5',  text: '    currency: "usd",', color: 'rgba(242,236,228,0.65)' },
  { num: '6',  text: '    source: order.card_token', color: 'rgba(242,236,228,0.65)' },
  { num: '7',  text: '  });', color: '#F2ECE4' },
  { num: '8',  text: '  return charge; // bug: no error handling!', color: '#FF5F56' },
  { num: '9',  text: '}', color: '#F2ECE4' },
];

// Approval stamp SVG
const Stamp: React.FC<{ opacity: number; scale: number }> = ({ opacity, scale }) => (
  <g
    transform={`translate(590, 68) rotate(-18) scale(${scale})`}
    opacity={opacity}
  >
    {/* Outer ring */}
    <circle cx="0" cy="0" r="80" fill="none" stroke={GREEN} strokeWidth="5" strokeDasharray="8 4"/>
    {/* Inner ring */}
    <circle cx="0" cy="0" r="66" fill="none" stroke={GREEN} strokeWidth="2" opacity="0.6"/>
    {/* Background */}
    <circle cx="0" cy="0" r="63" fill={GREEN} fillOpacity="0.08"/>
    {/* Checkmark */}
    <path d="M-28 0 L-8 20 L32 -20" stroke={GREEN} strokeWidth="7" strokeLinecap="round" strokeLinejoin="round" fill="none"/>
    {/* Text arc top */}
    <text
      textAnchor="middle" x="0" y="-38"
      fontSize="13" fontWeight="800" fill={GREEN}
      fontFamily="'SF Mono', monospace" letterSpacing="3"
    >APPROVED</text>
    {/* Text arc bottom */}
    <text
      textAnchor="middle" x="0" y="55"
      fontSize="11" fontWeight="600" fill={GREEN}
      fontFamily="'SF Mono', monospace" letterSpacing="2"
      opacity="0.72"
    >CODE REVIEW</text>
  </g>
);

export const Slide4_Ownership: React.FC = () => {
  const frame = useCurrentFrame();
  const { fps } = useVideoConfig();

  const sceneOp = fadeOut(frame, 285, 299);

  const h1Sp    = sp(frame, fps, 10, { stiffness: 68, damping: 14 });
  const h2Sp    = sp(frame, fps, 20, { stiffness: 68, damping: 14 });
  const h3Sp    = sp(frame, fps, 32, { stiffness: 68, damping: 14 });
  const codeSp  = sp(frame, fps, 48, { stiffness: 50, damping: 14 });
  const stampSp = sp(frame, fps, 88, { stiffness: 45, damping: 11 });
  const bsp     = BULLETS.map((_, i) =>
    sp(frame, fps, 120 + i * 18, { stiffness: 60, damping: 14 }),
  );

  return (
    <SceneCanvas opacity={sceneOp} background={<PastelBackground />}>


      {/* ── "If You Can't" ─────────────────────────────────────────────────── */}
      <div style={{
        position: 'absolute', top: 262, left: SAFE_H,
        opacity: interpolate(h1Sp, [0, 0.25], [0, 1]),
        transform: `translateY(${interpolate(h1Sp, [0, 1], [30, 0])}px)`,
        filter: blurFade(h1Sp, 12),
      }}>
        <span style={{ fontSize: 80, fontWeight: 900, fontFamily: FONT_HEAD, color: BLACK, letterSpacing: '-2.5px', lineHeight: 1 }}>
          If You Can't
        </span>
      </div>

      {/* ── "Explain It," ──────────────────────────────────────────────────── */}
      <div style={{
        position: 'absolute', top: 350, left: SAFE_H,
        opacity: interpolate(h2Sp, [0, 0.25], [0, 1]),
        transform: `translateY(${interpolate(h2Sp, [0, 1], [26, 0])}px)`,
        filter: blurFade(h2Sp, 12),
      }}>
        <span style={{ fontSize: 80, fontWeight: 900, fontFamily: FONT_HEAD, color: BLACK, letterSpacing: '-2.5px', lineHeight: 1 }}>
          Explain It,
        </span>
      </div>

      {/* ── "Don't Commit It." ─────────────────────────────────────────────── */}
      <div style={{
        position: 'absolute', top: 438, left: SAFE_H, right: SAFE_H,
        opacity: interpolate(h3Sp, [0, 0.25], [0, 1]),
        transform: `translateY(${interpolate(h3Sp, [0, 1], [22, 0])}px)`,
        filter: blurFade(h3Sp, 10),
      }}>
        <span style={{
          fontSize: 72, fontWeight: 900, fontFamily: FONT_HEAD, letterSpacing: '-2px', lineHeight: 1,
          background: `linear-gradient(135deg, ${ORANGE} 0%, #FFA040 100%)`,
          WebkitBackgroundClip: 'text', WebkitTextFillColor: 'transparent',
          backgroundClip: 'text', color: 'transparent',
        }}>
          Don't Commit It.
        </span>
      </div>

      {/* ── Code block + stamp ─────────────────────────────────────────────── */}
      <div style={{
        position: 'absolute', top: 546, left: SAFE_H, right: SAFE_H,
        opacity: interpolate(codeSp, [0, 0.30], [0, 1]),
        transform: `translateY(${interpolate(codeSp, [0, 1], [32, 0])}px)`,
        filter: blurFade(codeSp, 8),
      }}>
        {/* Code card */}
        <div style={{
          background: '#0F0C1A', borderRadius: 18, overflow: 'hidden',
          boxShadow: '0 10px 40px rgba(0,0,0,0.26), 0 0 0 1px rgba(255,255,255,0.06)',
          border: '1px solid rgba(255,130,60,0.14)',
        }}>
          {/* title bar */}
          <div style={{
            height: 40, background: '#18142A',
            display: 'flex', alignItems: 'center', padding: '0 16px', gap: 8,
          }}>
            <div style={{ width: 11, height: 11, borderRadius: '50%', background: '#FF5F56' }}/>
            <div style={{ width: 11, height: 11, borderRadius: '50%', background: '#FFBD2E' }}/>
            <div style={{ width: 11, height: 11, borderRadius: '50%', background: '#27C93F' }}/>
            <span style={{ fontSize: 13, fontFamily: FONT_MONO, color: 'rgba(255,255,255,0.35)', marginLeft: 6 }}>
              payment-service.ts — AI generated, awaiting review
            </span>
          </div>

          {/* code lines + stamp overlay */}
          <div style={{ position: 'relative', padding: '14px 18px' }}>
            {CODE_LINES.map((l, i) => (
              <div key={i} style={{ display: 'flex', gap: 12, marginBottom: 2 }}>
                <span style={{ fontSize: 13, fontFamily: FONT_MONO, color: 'rgba(255,255,255,0.22)', width: 14, textAlign: 'right', flexShrink: 0 }}>
                  {l.num}
                </span>
                <span style={{ fontSize: 13, fontFamily: FONT_MONO, color: l.color, lineHeight: 1.65 }}>{l.text}</span>
              </div>
            ))}

            {/* Stamp SVG overlay */}
            <svg
              style={{ position: 'absolute', top: 0, left: 0, width: '100%', height: '100%', pointerEvents: 'none' }}
              viewBox="0 0 756 210"
            >
              <Stamp
                opacity={interpolate(stampSp, [0, 0.35], [0, 1])}
                scale={interpolate(stampSp, [0, 1], [0.4, 1])}
              />
            </svg>
          </div>
        </div>
      </div>

      {/* ── Bullet points ──────────────────────────────────────────────────── */}
      <div style={{
        position: 'absolute', top: 884, left: SAFE_H, right: SAFE_H,
        background: 'rgba(255,255,255,0.86)',
        borderRadius: 24, padding: '22px 26px',
        boxShadow: '0 4px 24px rgba(0,0,0,0.06), 0 0 0 1.5px rgba(0,0,0,0.05)',
      }}>
        {BULLETS.map((b, i) => (
          <div key={i} style={{
            display: 'flex', gap: 14,
            marginBottom: i < BULLETS.length - 1 ? 18 : 0,
            opacity: interpolate(bsp[i], [0, 0.28], [0, 1]),
            transform: `translateX(${interpolate(bsp[i], [0, 1], [20, 0])}px)`,
          }}>
            <div style={{
              width: 8, height: 8, borderRadius: '50%', background: ORANGE,
              flexShrink: 0, marginTop: 14,
            }}/>
            <span style={{ fontSize: 30, fontFamily: FONT_HEAD, color: 'rgba(10,10,10,0.80)', lineHeight: 1.55 }}>
              <strong style={{ fontWeight: 800, color: BLACK }}>{b.bold}</strong>
              {b.rest}
            </span>
          </div>
        ))}
      </div>

    </SceneCanvas>
  );
};
